### ISSUE TITLE
DevX API Quality Improvements

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-devx-api#1332]
- [ ] Increase resource allocation for DevX API mainly memory
- [ ] Refine alerting threshold to reduce alerting fatigue
- [ ] Document DevX API quality investment scope of work
#956
